# Generated by Django 4.1.4 on 2022-12-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=50, verbose_name='Координаты')),
            ],
        ),
        migrations.CreateModel(
            name='DataHive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.FloatField(verbose_name='Влажность')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('hive_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hives.hive', verbose_name='Номер улья')),
            ],
            options={
                'ordering': ['-hive_id'],
            },
        ),
    ]
