# Generated by Django 4.1.4 on 2022-12-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0002_alter_hive_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('count_of_request', models.IntegerField(verbose_name='Количество запросов')),
            ],
            options={
                'ordering': ['-count_of_request'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Конец')),
                ('coast', models.FloatField(verbose_name='Стоимость')),
                ('hive_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hives.hive')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hives.service')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
