# Generated by Django 4.1.4 on 2022-12-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0003_service_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Номер')),
                ('valid', models.DateField(verbose_name='Срок действия')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV')),
            ],
        ),
        migrations.CreateModel(
            name='ReportHive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aver_temp', models.FloatField(verbose_name='Ср температура')),
                ('aver_humid', models.FloatField(verbose_name='Ср влажность')),
                ('change_weight', models.FloatField(verbose_name='Изм веса')),
                ('hive_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hives.hive', verbose_name='Улей')),
            ],
            options={
                'ordering': ['hive_id'],
            },
        ),
    ]
