# Generated by Django 4.1.4 on 2022-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0004_card_reporthive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['hive_id']},
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=19, verbose_name='Номер'),
        ),
    ]
