# Generated by Django 4.1.4 on 2022-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0005_alter_subscription_options_alter_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthive',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='reporthive',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Начало'),
        ),
    ]
